function PicturesAPI() {
  return [
    {
      id: 0,
      user_id: 0,
      like: 15,
      category: "entree",
      name: "cordon bleu",
      DateTime: "09/12/23 16h30",
      img: "cordon-bleu.png",
    },
    {
      id: 1,
      user_id: 2,
      like: 6,
      category: "plat",
      name: "frites",
      DateTime: "12/12/23 09h00",
      img: "frites.png",
    },
    {
      id: 2,
      user_id: 2,
      like: 50,
      category: "dessert",
      name: "panacota",
      DateTime: "13/12/23 17h00",
      img: "panacota.png",
    },
    {
      id: 3,
      user_id: 2,
      like: 13,
      category: "dessert",
      name: "fraisier",
      DateTime: "13/12/23 18h00",
      img: "fraisier.png",
    },
    {
      id: 5,
      user_id: 3,
      like: 8,
      category: "dessert",
      name: "crepe",
      DateTime: "14/12/23 15h45",
      img: "crepe.png",
    },
    {
      id: 6,
      user_id: 4,
      like: 12,
      category: "boisson",
      name: "mojito",
      DateTime: "15/12/23 20h15",
      img: "mojito.png",
    },
    {
      id: 7,
      user_id: 5,
      like: 7,
      category: "entree",
      name: "nem",
      DateTime: "15/12/23 19h00",
      img: "nem.png",
    },
    {
      id: 8,
      user_id: 6,
      like: 18,
      category: "plat",
      name: "quiche lorraine",
      DateTime: "16/12/23 13h45",
      img: "quiche-lorraine.png",
    },
    {
      id: 9,
      user_id: 7,
      like: 10,
      category: "plat",
      name: "ravioli",
      DateTime: "16/12/23 18h30",
      img: "ravioli.png",
    },
  ];
}

export default PicturesAPI;
